# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-ubuntu18
      - test-ubuntu16
      - test-centos7
      - test-debian9

jobs:
  test-ubuntu18:
    docker:
      - image: circleci/buildpack-deps:18.04
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get install -qq -y g++ sox
      - run: ./run.sh
      - run: cp -r ./kaldi/src/featbin .
      - run: rm featbin/*.cc featbin/*.o
      - run: tar -zcvf ubuntu18-featbin.tar.gz featbin
      - store_artifacts:
          path: ubuntu18-featbin.tar.gz

  test-ubuntu16:
    docker:
      - image: circleci/buildpack-deps:16.04
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get install -qq -y g++ sox python3
      - run: ./run.sh
      - run: cp -r ./kaldi/src/featbin .
      - run: rm featbin/*.cc featbin/*.o
      - run: tar -zcvf ubuntu16-featbin.tar.gz featbin
      - store_artifacts:
          path: ubuntu16-featbin.tar.gz

  test-debian9:
    docker:
      - image: debian:9
    working_directory: ~/repo
    steps:
      - checkout
      - run: apt-get install -qq -y g++ sox unzip bzip2 wget curl sudo
      - run: ./run.sh
      - run: cp -r ./kaldi/src/featbin .
      - run: rm featbin/*.cc featbin/*.o
      - run: tar -zcvf debian9-featbin.tar.gz featbin
      - store_artifacts:
          path: debian9-featbin.tar.gz

  test-centos7:
    docker:
      - image: centos:7
        environment:
          CC: /opt/rh/devtoolset-7/root/usr/bin/gcc
          CXX: /opt/rh/devtoolset-7/root/usr/bin/g++
    working_directory: ~/repo
    steps:
      - run:
          name: Install dependencies
          command: |
            yum install -y https://centos7.iuscommunity.org/ius-release.rpm
            yum install -y git centos-release-scl make bzip2 wget which unzip zlib-devel automake autoconf patch sox libtool subversion python36u
            yum-config-manager --enable rhel-server-rhscl-7-rpms
            yum install -y devtoolset-7-gcc-c++
      - checkout
      - run:
          name: run.sh
          command: |
            # NOTE(karita) this line exited 1
            # source scl_source enable devtoolset-7
            PATH="/opt/rh/devtoolset-7/root/usr/bin:${PATH:-}"
            ./run.sh
      - run: ./run.sh
      - run: cp -r ./kaldi/src/featbin .
      - run: rm featbin/*.cc featbin/*.o
      - run: tar -zcvf centos7-featbin.tar.gz featbin
      - store_artifacts:
          path: centos7-featbin.tar.gz

  # test-debian9:
  #   docker:
  #     - image: debian:9
  #       environment:
  #         ESPNET_PYTHON_VERSION: 3.7
  #         TH_VERSION: 1.1.0
  #         CHAINER_VERSION: 5.0.0
  #         USE_CONDA: true
  #         CC: gcc-6
  #         CXX: g++-6
  #   working_directory: ~/repo

  #   steps:
  #     - checkout
  #     - run:
  #         name: run tests
  #         command: |
  #           apt-get update -qq
  #           apt-get install -qq -y git cmake g++-6 libsndfile1-dev unzip bzip2 wget curl
  #         ./run.sh
